# Generated by Django 4.1.3 on 2022-12-07 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Healthy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('body', models.CharField(max_length=250, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('Calories', models.IntegerField(null=True)),
            ],
        ),
    ]
